### ISSUE TITLE
Absolute path found when compiling

### ISSUE THREAD

**Issue by MetARverse-Ian** [AnkitSharma-007/ASPCore.BlazorCrud#1]
C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(197,5): error : Assets file 'c:\users\asharma2\source\repos\BlazorCrud\BlazorCrud.Shared\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

**Comment by AnkitSharma-007** [comment]
Update the application to the latest version of Blazor and it will resolve the issue.
